AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Serverless Java17 Quarkus Native Image Web Adapter Container Example

Globals:
  Function:
    Timeout: 10

Resources:
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "awsdevday2023tokyo-sls-framework-web-adapter-native-image"
      PackageType: Image
      MemorySize: 2048
      Tracing: Active
      Environment:
        Variables:
          RUST_LOG: info
          READINESS_CHECK_PATH: /hello
          REMOVE_BASE_PATH: /v1
      AutoPublishAlias: live
      DeploymentPreference:
        Type: AllAtOnce
      Events:
        Root:
          Type: HttpApi
          Properties:
            Path: /v1
            Method: ANY
        Api:
          Type: HttpApi
          Properties:
            Path: /v1/{proxy+}
            Method: ANY
    Metadata:
      DockerTag: awsdevday2023tokyo-sls-framework-web-adapter-native-image
      DockerContext: ./
      Dockerfile: Dockerfile

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/v1/hello"
